export interface Surah {
  id: number;
  name: string;
  englishName: string;
  ayahs: number;
  revelationType: "مكية" | "مدنية";
  theme:
    | "indigo"
    | "emerald"
    | "amber"
    | "rose"
    | "cyan"
    | "violet";

  favorite: boolean;
  progress: number;
}

export const surahs: Surah[] = [
  {
    id: 1,
    name: "الفاتحة",
    englishName: "Al-Fatihah",
    ayahs: 7,
    revelationType: "مكية",
    theme: "indigo",
    favorite: false,
    progress: 0,
  },

  {
    id: 2,
    name: "البقرة",
    englishName: "Al-Baqarah",
    ayahs: 286,
    revelationType: "مدنية",
    theme: "emerald",
    favorite: false,
    progress: 0,
  },

  {
    id: 3,
    name: "آل عمران",
    englishName: "Ali 'Imran",
    ayahs: 200,
    revelationType: "مدنية",
    theme: "amber",
    favorite: false,
    progress: 0,
  },

  {
    id: 4,
    name: "النساء",
    englishName: "An-Nisa",
    ayahs: 176,
    revelationType: "مدنية",
    theme: "rose",
    favorite: false,
    progress: 0,
  },

  {
    id: 5,
    name: "المائدة",
    englishName: "Al-Ma'idah",
    ayahs: 120,
    revelationType: "مدنية",
    theme: "cyan",
    favorite: false,
    progress: 0,
  },

  {
    id: 6,
    name: "الأنعام",
    englishName: "Al-An'am",
    ayahs: 165,
    revelationType: "مكية",
    theme: "violet",
    favorite: false,
    progress: 0,
  },

  {
    id: 7,
    name: "الأعراف",
    englishName: "Al-A'raf",
    ayahs: 206,
    revelationType: "مكية",
    theme: "indigo",
    favorite: false,
    progress: 0,
  },

  {
    id: 8,
    name: "الأنفال",
    englishName: "Al-Anfal",
    ayahs: 75,
    revelationType: "مدنية",
    theme: "emerald",
    favorite: false,
    progress: 0,
  },{
    id: 9,
    name: "التوبة",
    englishName: "At-Tawbah",
    ayahs: 129,
    revelationType: "مدنية",
    theme: "amber",
    favorite: false,
    progress: 0,
  },

  {
    id: 10,
    name: "يونس",
    englishName: "Yunus",
    ayahs: 109,
    revelationType: "مكية",
    theme: "cyan",
    favorite: false,
    progress: 0,
  },

  {
    id: 11,
    name: "هود",
    englishName: "Hud",
    ayahs: 123,
    revelationType: "مكية",
    theme: "violet",
    favorite: false,
    progress: 0,
  },

  {
    id: 12,
    name: "يوسف",
    englishName: "Yusuf",
    ayahs: 111,
    revelationType: "مكية",
    theme: "indigo",
    favorite: false,
    progress: 0,
  },

  {
    id: 13,
    name: "الرعد",
    englishName: "Ar-Ra'd",
    ayahs: 43,
    revelationType: "مدنية",
    theme: "emerald",
    favorite: false,
    progress: 0,
  },

  {
    id: 14,
    name: "إبراهيم",
    englishName: "Ibrahim",
    ayahs: 52,
    revelationType: "مكية",
    theme: "rose",
    favorite: false,
    progress: 0,
  },

  {
    id: 15,
    name: "الحجر",
    englishName: "Al-Hijr",
    ayahs: 99,
    revelationType: "مكية",
    theme: "amber",
    favorite: false,
    progress: 0,
  },

  {
    id: 16,
    name: "النحل",
    englishName: "An-Nahl",
    ayahs: 128,
    revelationType: "مكية",
    theme: "cyan",
    favorite: false,
    progress: 0,
  },{
    id: 17,
    name: "الإسراء",
    englishName: "Al-Isra",
    ayahs: 111,
    revelationType: "مكية",
    theme: "violet",
    favorite: false,
    progress: 0,
  },

  {
    id: 18,
    name: "الكهف",
    englishName: "Al-Kahf",
    ayahs: 110,
    revelationType: "مكية",
    theme: "emerald",
    favorite: false,
    progress: 0,
  },

  {
    id: 19,
    name: "مريم",
    englishName: "Maryam",
    ayahs: 98,
    revelationType: "مكية",
    theme: "rose",
    favorite: false,
    progress: 0,
  },

  {
    id: 20,
    name: "طه",
    englishName: "Ta-Ha",
    ayahs: 135,
    revelationType: "مكية",
    theme: "amber",
    favorite: false,
    progress: 0,
  },

  {
    id: 21,
    name: "الأنبياء",
    englishName: "Al-Anbiya",
    ayahs: 112,
    revelationType: "مكية",
    theme: "indigo",
    favorite: false,
    progress: 0,
  },

  {
    id: 22,
    name: "الحج",
    englishName: "Al-Hajj",
    ayahs: 78,
    revelationType: "مدنية",
    theme: "cyan",
    favorite: false,
    progress: 0,
  },

  {
    id: 23,
    name: "المؤمنون",
    englishName: "Al-Mu'minun",
    ayahs: 118,
    revelationType: "مكية",
    theme: "emerald",
    favorite: false,
    progress: 0,
  },

  {
    id: 24,
    name: "النور",
    englishName: "An-Nur",
    ayahs: 64,
    revelationType: "مدنية",
    theme: "amber",
    favorite: false,
    progress: 0,
  },{
    id: 25,
    name: "الفرقان",
    englishName: "Al-Furqan",
    ayahs: 77,
    revelationType: "مكية",
    theme: "violet",
    favorite: false,
    progress: 0,
  },

  {
    id: 26,
    name: "الشعراء",
    englishName: "Ash-Shu'ara",
    ayahs: 227,
    revelationType: "مكية",
    theme: "rose",
    favorite: false,
    progress: 0,
  },

  {
    id: 27,
    name: "النمل",
    englishName: "An-Naml",
    ayahs: 93,
    revelationType: "مكية",
    theme: "amber",
    favorite: false,
    progress: 0,
  },

  {
    id: 28,
    name: "القصص",
    englishName: "Al-Qasas",
    ayahs: 88,
    revelationType: "مكية",
    theme: "emerald",
    favorite: false,
    progress: 0,
  },

  {
    id: 29,
    name: "العنكبوت",
    englishName: "Al-'Ankabut",
    ayahs: 69,
    revelationType: "مكية",
    theme: "cyan",
    favorite: false,
    progress: 0,
  },

  {
    id: 30,
    name: "الروم",
    englishName: "Ar-Rum",
    ayahs: 60,
    revelationType: "مكية",
    theme: "indigo",
    favorite: false,
    progress: 0,
  },

  {
    id: 31,
    name: "لقمان",
    englishName: "Luqman",
    ayahs: 34,
    revelationType: "مكية",
    theme: "amber",
    favorite: false,
    progress: 0,
  },

  {
    id: 32,
    name: "السجدة",
    englishName: "As-Sajdah",
    ayahs: 30,
    revelationType: "مكية",
    theme: "violet",
    favorite: false,
    progress: 0,
  },{
    id: 33,
    name: "الأحزاب",
    englishName: "Al-Ahzab",
    ayahs: 73,
    revelationType: "مدنية",
    theme: "emerald",
    favorite: false,
    progress: 0,
  },

  {
    id: 34,
    name: "سبأ",
    englishName: "Saba",
    ayahs: 54,
    revelationType: "مكية",
    theme: "amber",
    favorite: false,
    progress: 0,
  },

  {
    id: 35,
    name: "فاطر",
    englishName: "Fatir",
    ayahs: 45,
    revelationType: "مكية",
    theme: "rose",
    favorite: false,
    progress: 0,
  },

  {
    id: 36,
    name: "يس",
    englishName: "Ya-Sin",
    ayahs: 83,
    revelationType: "مكية",
    theme: "indigo",
    favorite: false,
    progress: 0,
  },

  {
    id: 37,
    name: "الصافات",
    englishName: "As-Saffat",
    ayahs: 182,
    revelationType: "مكية",
    theme: "cyan",
    favorite: false,
    progress: 0,
  },

  {
    id: 38,
    name: "ص",
    englishName: "Sad",
    ayahs: 88,
    revelationType: "مكية",
    theme: "violet",
    favorite: false,
    progress: 0,
  },

  {
    id: 39,
    name: "الزمر",
    englishName: "Az-Zumar",
    ayahs: 75,
    revelationType: "مكية",
    theme: "emerald",
    favorite: false,
    progress: 0,
  },

  {
    id: 40,
    name: "غافر",
    englishName: "Ghafir",
    ayahs: 85,
    revelationType: "مكية",
    theme: "amber",
    favorite: false,
    progress: 0,
  },{
    id: 41,
    name: "فصلت",
    englishName: "Fussilat",
    ayahs: 54,
    revelationType: "مكية",
    theme: "rose",
    favorite: false,
    progress: 0,
  },

  {
    id: 42,
    name: "الشورى",
    englishName: "Ash-Shura",
    ayahs: 53,
    revelationType: "مكية",
    theme: "indigo",
    favorite: false,
    progress: 0,
  },

  {
    id: 43,
    name: "الزخرف",
    englishName: "Az-Zukhruf",
    ayahs: 89,
    revelationType: "مكية",
    theme: "cyan",
    favorite: false,
    progress: 0,
  },

  {
    id: 44,
    name: "الدخان",
    englishName: "Ad-Dukhan",
    ayahs: 59,
    revelationType: "مكية",
    theme: "amber",
    favorite: false,
    progress: 0,
  },

  {
    id: 45,
    name: "الجاثية",
    englishName: "Al-Jathiyah",
    ayahs: 37,
    revelationType: "مكية",
    theme: "emerald",
    favorite: false,
    progress: 0,
  },

  {
    id: 46,
    name: "الأحقاف",
    englishName: "Al-Ahqaf",
    ayahs: 35,
    revelationType: "مكية",
    theme: "violet",
    favorite: false,
    progress: 0,
  },

  {
    id: 47,
    name: "محمد",
    englishName: "Muhammad",
    ayahs: 38,
    revelationType: "مدنية",
    theme: "indigo",
    favorite: false,
    progress: 0,
  },

  {
    id: 48,
    name: "الفتح",
    englishName: "Al-Fath",
    ayahs: 29,
    revelationType: "مدنية",
    theme: "rose",
    favorite: false,
    progress: 0,
  },{
    id: 49,
    name: "الحجرات",
    englishName: "Al-Hujurat",
    ayahs: 18,
    revelationType: "مدنية",
    theme: "cyan",
    favorite: false,
    progress: 0,
  },

  {
    id: 50,
    name: "ق",
    englishName: "Qaf",
    ayahs: 45,
    revelationType: "مكية",
    theme: "amber",
    favorite: false,
    progress: 0,
  },

  {
    id: 51,
    name: "الذاريات",
    englishName: "Adh-Dhariyat",
    ayahs: 60,
    revelationType: "مكية",
    theme: "violet",
    favorite: false,
    progress: 0,
  },

  {
    id: 52,
    name: "الطور",
    englishName: "At-Tur",
    ayahs: 49,
    revelationType: "مكية",
    theme: "rose",
    favorite: false,
    progress: 0,
  },

  {
    id: 53,
    name: "النجم",
    englishName: "An-Najm",
    ayahs: 62,
    revelationType: "مكية",
    theme: "indigo",
    favorite: false,
    progress: 0,
  },

  {
    id: 54,
    name: "القمر",
    englishName: "Al-Qamar",
    ayahs: 55,
    revelationType: "مكية",
    theme: "emerald",
    favorite: false,
    progress: 0,
  },

  {
    id: 55,
    name: "الرحمن",
    englishName: "Ar-Rahman",
    ayahs: 78,
    revelationType: "مدنية",
    theme: "cyan",
    favorite: false,
    progress: 0,
  },

  {
    id: 56,
    name: "الواقعة",
    englishName: "Al-Waqi'ah",
    ayahs: 96,
    revelationType: "مكية",
    theme: "amber",
    favorite: false,
    progress: 0,
  },{
    id: 57,
    name: "الحديد",
    englishName: "Al-Hadid",
    ayahs: 29,
    revelationType: "مدنية",
    theme: "emerald",
    favorite: false,
    progress: 0,
  },

  {
    id: 58,
    name: "المجادلة",
    englishName: "Al-Mujadila",
    ayahs: 22,
    revelationType: "مدنية",
    theme: "violet",
    favorite: false,
    progress: 0,
  },

  {
    id: 59,
    name: "الحشر",
    englishName: "Al-Hashr",
    ayahs: 24,
    revelationType: "مدنية",
    theme: "rose",
    favorite: false,
    progress: 0,
  },

  {
    id: 60,
    name: "الممتحنة",
    englishName: "Al-Mumtahanah",
    ayahs: 13,
    revelationType: "مدنية",
    theme: "cyan",
    favorite: false,
    progress: 0,
  },

  {
    id: 61,
    name: "الصف",
    englishName: "As-Saff",
    ayahs: 14,
    revelationType: "مدنية",
    theme: "amber",
    favorite: false,
    progress: 0,
  },

  {
    id: 62,
    name: "الجمعة",
    englishName: "Al-Jumu'ah",
    ayahs: 11,
    revelationType: "مدنية",
    theme: "indigo",
    favorite: false,
    progress: 0,
  },

  {
    id: 63,
    name: "المنافقون",
    englishName: "Al-Munafiqun",
    ayahs: 11,
    revelationType: "مدنية",
    theme: "emerald",
    favorite: false,
    progress: 0,
  },

  {
    id: 64,
    name: "التغابن",
    englishName: "At-Taghabun",
    ayahs: 18,
    revelationType: "مدنية",
    theme: "amber",
    favorite: false,
    progress: 0,
  },

  {
    id: 65,
    name: "الطلاق",
    englishName: "At-Talaq",
    ayahs: 12,
    revelationType: "مدنية",
    theme: "rose",
    favorite: false,
    progress: 0,
  },

  {
    id: 66,
    name: "التحريم",
    englishName: "At-Tahrim",
    ayahs: 12,
    revelationType: "مدنية",
    theme: "violet",
    favorite: false,
    progress: 0,
  },{
    id: 67,
    name: "الملك",
    englishName: "Al-Mulk",
    ayahs: 30,
    revelationType: "مكية",
    theme: "indigo",
    favorite: false,
    progress: 0,
  },

  {
    id: 68,
    name: "القلم",
    englishName: "Al-Qalam",
    ayahs: 52,
    revelationType: "مكية",
    theme: "amber",
    favorite: false,
    progress: 0,
  },

  {
    id: 69,
    name: "الحاقة",
    englishName: "Al-Haqqah",
    ayahs: 52,
    revelationType: "مكية",
    theme: "rose",
    favorite: false,
    progress: 0,
  },

  {
    id: 70,
    name: "المعارج",
    englishName: "Al-Ma'arij",
    ayahs: 44,
    revelationType: "مكية",
    theme: "cyan",
    favorite: false,
    progress: 0,
  },

  {
    id: 71,
    name: "نوح",
    englishName: "Nuh",
    ayahs: 28,
    revelationType: "مكية",
    theme: "emerald",
    favorite: false,
    progress: 0,
  },

  {
    id: 72,
    name: "الجن",
    englishName: "Al-Jinn",
    ayahs: 28,
    revelationType: "مكية",
    theme: "violet",
    favorite: false,
    progress: 0,
  },

  {
    id: 73,
    name: "المزمل",
    englishName: "Al-Muzzammil",
    ayahs: 20,
    revelationType: "مكية",
    theme: "indigo",
    favorite: false,
    progress: 0,
  },

  {
    id: 74,
    name: "المدثر",
    englishName: "Al-Muddaththir",
    ayahs: 56,
    revelationType: "مكية",
    theme: "amber",
    favorite: false,
    progress: 0,
  },

  {
    id: 75,
    name: "القيامة",
    englishName: "Al-Qiyamah",
    ayahs: 40,
    revelationType: "مكية",
    theme: "rose",
    favorite: false,
    progress: 0,
  },

  {
    id: 76,
    name: "الإنسان",
    englishName: "Al-Insan",
    ayahs: 31,
    revelationType: "مدنية",
    theme: "cyan",
    favorite: false,
    progress: 0,
  },

  {
    id: 77,
    name: "المرسلات",
    englishName: "Al-Mursalat",
    ayahs: 50,
    revelationType: "مكية",
    theme: "emerald",
    favorite: false,
    progress: 0,
  },{
    id: 78,
    name: "النبأ",
    englishName: "An-Naba",
    ayahs: 40,
    revelationType: "مكية",
    theme: "violet",
    favorite: false,
    progress: 0,
  },

  {
    id: 79,
    name: "النازعات",
    englishName: "An-Nazi'at",
    ayahs: 46,
    revelationType: "مكية",
    theme: "indigo",
    favorite: false,
    progress: 0,
  },

  {
    id: 80,
    name: "عبس",
    englishName: "Abasa",
    ayahs: 42,
    revelationType: "مكية",
    theme: "amber",
    favorite: false,
    progress: 0,
  },

  {
    id: 81,
    name: "التكوير",
    englishName: "At-Takwir",
    ayahs: 29,
    revelationType: "مكية",
    theme: "rose",
    favorite: false,
    progress: 0,
  },

  {
    id: 82,
    name: "الانفطار",
    englishName: "Al-Infitar",
    ayahs: 19,
    revelationType: "مكية",
    theme: "cyan",
    favorite: false,
    progress: 0,
  },

  {
    id: 83,
    name: "المطففين",
    englishName: "Al-Mutaffifin",
    ayahs: 36,
    revelationType: "مكية",
    theme: "emerald",
    favorite: false,
    progress: 0,
  },

  {
    id: 84,
    name: "الانشقاق",
    englishName: "Al-Inshiqaq",
    ayahs: 25,
    revelationType: "مكية",
    theme: "violet",
    favorite: false,
    progress: 0,
  },

  {
    id: 85,
    name: "البروج",
    englishName: "Al-Buruj",
    ayahs: 22,
    revelationType: "مكية",
    theme: "indigo",
    favorite: false,
    progress: 0,
  },

  {
    id: 86,
    name: "الطارق",
    englishName: "At-Tariq",
    ayahs: 17,
    revelationType: "مكية",
    theme: "amber",
    favorite: false,
    progress: 0,
  },

  {
    id: 87,
    name: "الأعلى",
    englishName: "Al-A'la",
    ayahs: 19,
    revelationType: "مكية",
    theme: "rose",
    favorite: false,
    progress: 0,
  },

  {
    id: 88,
    name: "الغاشية",
    englishName: "Al-Ghashiyah",
    ayahs: 26,
    revelationType: "مكية",
    theme: "cyan",
    favorite: false,
    progress: 0,
  },{
    id: 89,
    name: "الفجر",
    englishName: "Al-Fajr",
    ayahs: 30,
    revelationType: "مكية",
    theme: "emerald",
    favorite: false,
    progress: 0,
  },

  {
    id: 90,
    name: "البلد",
    englishName: "Al-Balad",
    ayahs: 20,
    revelationType: "مكية",
    theme: "amber",
    favorite: false,
    progress: 0,
  },

  {
    id: 91,
    name: "الشمس",
    englishName: "Ash-Shams",
    ayahs: 15,
    revelationType: "مكية",
    theme: "rose",
    favorite: false,
    progress: 0,
  },

  {
    id: 92,
    name: "الليل",
    englishName: "Al-Layl",
    ayahs: 21,
    revelationType: "مكية",
    theme: "indigo",
    favorite: false,
    progress: 0,
  },

  {
    id: 93,
    name: "الضحى",
    englishName: "Ad-Duhaa",
    ayahs: 11,
    revelationType: "مكية",
    theme: "cyan",
    favorite: false,
    progress: 0,
  },

  {
    id: 94,
    name: "الشرح",
    englishName: "Ash-Sharh",
    ayahs: 8,
    revelationType: "مكية",
    theme: "violet",
    favorite: false,
    progress: 0,
  },

  {
    id: 95,
    name: "التين",
    englishName: "At-Tin",
    ayahs: 8,
    revelationType: "مكية",
    theme: "emerald",
    favorite: false,
    progress: 0,
  },

  {
    id: 96,
    name: "العلق",
    englishName: "Al-'Alaq",
    ayahs: 19,
    revelationType: "مكية",
    theme: "amber",
    favorite: false,
    progress: 0,
  },

  {
    id: 97,
    name: "القدر",
    englishName: "Al-Qadr",
    ayahs: 5,
    revelationType: "مكية",
    theme: "rose",
    favorite: false,
    progress: 0,
  },

  {
    id: 98,
    name: "البينة",
    englishName: "Al-Bayyinah",
    ayahs: 8,
    revelationType: "مدنية",
    theme: "indigo",
    favorite: false,
    progress: 0,
  },

  {
    id: 99,
    name: "الزلزلة",
    englishName: "Az-Zalzalah",
    ayahs: 8,
    revelationType: "مدنية",
    theme: "cyan",
    favorite: false,
    progress: 0,
  },

  {
    id: 100,
    name: "العاديات",
    englishName: "Al-'Adiyat",
    ayahs: 11,
    revelationType: "مكية",
    theme: "violet",
    favorite: false,
    progress: 0,
  },

  {
    id: 101,
    name: "القارعة",
    englishName: "Al-Qari'ah",
    ayahs: 11,
    revelationType: "مكية",
    theme: "emerald",
    favorite: false,
    progress: 0,
  },

  {
    id: 102,
    name: "التكاثر",
    englishName: "At-Takathur",
    ayahs: 8,
    revelationType: "مكية",
    theme: "amber",
    favorite: false,
    progress: 0,
  },

  {
    id: 103,
    name: "العصر",
    englishName: "Al-'Asr",
    ayahs: 3,
    revelationType: "مكية",
    theme: "rose",
    favorite: false,
    progress: 0,
  },

  {
    id: 104,
    name: "الهمزة",
    englishName: "Al-Humazah",
    ayahs: 9,
    revelationType: "مكية",
    theme: "indigo",
    favorite: false,
    progress: 0,
  },

  {
    id: 105,
    name: "الفيل",
    englishName: "Al-Fil",
    ayahs: 5,
    revelationType: "مكية",
    theme: "cyan",
    favorite: false,
    progress: 0,
  },

  {
    id: 106,
    name: "قريش",
    englishName: "Quraysh",
    ayahs: 4,
    revelationType: "مكية",
    theme: "violet",
    favorite: false,
    progress: 0,
  },

  {
    id: 107,
    name: "الماعون",
    englishName: "Al-Ma'un",
    ayahs: 7,
    revelationType: "مكية",
    theme: "emerald",
    favorite: false,
    progress: 0,
  },

  {
    id: 108,
    name: "الكوثر",
    englishName: "Al-Kawthar",
    ayahs: 3,
    revelationType: "مكية",
    theme: "amber",
    favorite: false,
    progress: 0,
  },

  {
    id: 109,
    name: "الكافرون",
    englishName: "Al-Kafirun",
    ayahs: 6,
    revelationType: "مكية",
    theme: "rose",
    favorite: false,
    progress: 0,
  },{
    id: 110,
    name: "النصر",
    englishName: "An-Nasr",
    ayahs: 3,
    revelationType: "مدنية",
    theme: "indigo",
    favorite: false,
    progress: 0,
  },

  {
    id: 111,
    name: "المسد",
    englishName: "Al-Masad",
    ayahs: 5,
    revelationType: "مكية",
    theme: "amber",
    favorite: false,
    progress: 0,
  },

  {
    id: 112,
    name: "الإخلاص",
    englishName: "Al-Ikhlas",
    ayahs: 4,
    revelationType: "مكية",
    theme: "emerald",
    favorite: false,
    progress: 0,
  },

  {
    id: 113,
    name: "الفلق",
    englishName: "Al-Falaq",
    ayahs: 5,
    revelationType: "مكية",
    theme: "rose",
    favorite: false,
    progress: 0,
  },

  {
    id: 114,
    name: "الناس",
    englishName: "An-Nas",
    ayahs: 6,
    revelationType: "مكية",
    theme: "cyan",
    favorite: false,
    progress: 0,
  },
];